apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tf-testbed-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  volumeClaimGC:
    strategy: OnWorkflowCompletion
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 64Mi
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    dag:
      tasks:
      - name: terraform
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/tf-testbed.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
        templateRef:
          name: flavor-terraform-template
          template: "{{inputs.parameters.git_ref_type}}"
        withItems:
        - { platform: alpine_3.14 }

